# Generated by Django 4.0.2 on 2022-05-01 05:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_reviewratting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewRatting',
            new_name='ReviewRating',
        ),
        migrations.RenameField(
            model_name='reviewrating',
            old_name='ratting',
            new_name='rating',
        ),
    ]
